# Generated by Django 6.0.4 on 2026-05-07 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_urun_red_sebebi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_zamani', models.DateTimeField(default=django.utils.timezone.now)),
                ('bitis_zamani', models.DateTimeField()),
                ('mevcut_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('kazanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kazanilan_muzayedeler', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(limit_choices_to={'durum': 'aktif'}, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='products.urun')),
            ],
            options={
                'verbose_name': 'Müzayede',
                'verbose_name_plural': 'Müzayedeler',
            },
        ),
    ]
