# Generated by Django 6.0.4 on 2026-05-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name': 'Muzayede', 'verbose_name_plural': 'Muzayedeler'},
        ),
    ]
