# Generated by Django 6.0.4 on 2026-04-27 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('ust_kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.kategori', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('baslangicFiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Başlangıç Fiyatı')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('onay_bekliyor', 'Onay Bekliyor'), ('aktif', 'Aktif'), ('satildi', 'Satıldı'), ('reddedildi', 'Reddedildi'), ('suresi_doldu', 'Süresi Doldu')], default='onay_bekliyor', max_length=20, verbose_name='Durum')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='urun_gorselleri/', verbose_name='Görsel')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urunler', to='products.kategori', verbose_name='Kategori')),
                ('satici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
