# Generated by Django 6.0.4 on 2026-05-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='red_sebebi',
            field=models.TextField(blank=True, help_text='Eğer ürün reddedilirse, satıcıya gösterilecek sebep.', null=True, verbose_name='Reddedilme Sebebi'),
        ),
    ]
