# Generated by Django 6.0.4 on 2026-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_urun_red_sebebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='artis_adimi',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Tekliflerin kaç TL aralıklarla artacağını belirler.', max_digits=10, verbose_name='Artış Adımı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='teklif_suresi_gun',
            field=models.PositiveIntegerField(default=7, help_text='Ürün onaylandıktan sonra müzayedenin kaç gün açık kalacağı.', verbose_name='Teklif Süresi (Gün)'),
        ),
    ]
