# Generated by Django 6.0.4 on 2026-05-12 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0002_alter_auction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teklif Miktari')),
                ('durum', models.CharField(choices=[('GECERLI', 'Aktif / En Yuksek Teklif'), ('GECILDI', 'Gecildi'), ('IPTAL', 'Iptal Edildi')], default='GECERLI', max_length=10, verbose_name='Teklif Durumu')),
                ('zaman', models.DateTimeField(auto_now_add=True, verbose_name='Teklif Zamani')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifler', to='auction.auction', verbose_name='Muzayede')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklifleri', to=settings.AUTH_USER_MODEL, verbose_name='Teklif Veren')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
                'ordering': ['-miktar', '-zaman'],
            },
        ),
        migrations.CreateModel(
            name='BidIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artis_adimi', models.DecimalField(decimal_places=2, default=1, help_text='Yeni teklif, mevcut fiyatin en az bu miktar kadar uzerinde olmalidir.', max_digits=10, verbose_name='Artis Adimi')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teklif_ayari', to='auction.auction', verbose_name='Muzayede')),
            ],
            options={
                'verbose_name': 'Teklif Artis Ayari',
                'verbose_name_plural': 'Teklif Artis Ayarlari',
            },
        ),
        migrations.CreateModel(
            name='BidStatusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.CharField(max_length=255, verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to='bids.bid', verbose_name='Teklif')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teklif_bildirimleri', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
            options={
                'verbose_name': 'Teklif Bildirimi',
                'verbose_name_plural': 'Teklif Bildirimleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'durum'], name='bids_bid_auction_a7cfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['kullanici', 'durum'], name='bids_bid_kullani_2865cb_idx'),
        ),
    ]
