# Generated by Django 6.0.4 on 2026-05-08 09:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakiye', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12, verbose_name='Sahte Para Bakiyesi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
            options={
                'verbose_name': 'Cuzdan',
                'verbose_name_plural': 'Cuzdanlar',
            },
        ),
    ]
